import 'food_item.dart';

final List<FoodItem> mockFoodItems = [
  FoodItem(
    id: '1',
    name: 'Gourmet Pepperoni Pizza',
    description: 'Crisp artisan sourdough crust topped with house-made marinara sauce, aged mozzarella cheese, spicy Italian pepperoni slices, and fresh basil leaves.',
    price: 14.99,
    imageUrl: 'https://images.unsplash.com/photo-1628840042765-356cda07504e?w=800&auto=format&fit=crop&q=80',
    rating: 4.8,
    prepTime: '20-25 min',
    category: 'Pizza',
    sizes: ['Small', 'Medium', 'Large'],
    extras: ['Extra Mozzarella', 'Spicy Pepperoni', 'Truffle Oil'],
  ),
  FoodItem(
    id: '2',
    name: 'Truffle Wagyu Burger',
    description: 'Prime dry-aged Wagyu beef patty cooked to juicy perfection, layers of melted Swiss gruyere, caramelized balsamic onions, and rich black truffle aioli on a toasted brioche bun.',
    price: 18.50,
    imageUrl: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    prepTime: '15-20 min',
    category: 'Burgers',
    sizes: ['Single', 'Double', 'Triple'],
    extras: ['Crispy Bacon', 'Avocado Slices', 'Fried Egg'],
  ),
  FoodItem(
    id: '3',
    name: 'Signature Dragon Roll',
    description: 'Delectable tempura shrimp and cucumber wrapped inside, topped with fresh avocado slices, premium unagi eel, sesame seeds, and drizzled with sweet unagi sauce.',
    price: 16.99,
    imageUrl: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?w=800&auto=format&fit=crop&q=80',
    rating: 4.7,
    prepTime: '25-30 min',
    category: 'Sushi',
    sizes: ['8 Pieces', '12 Pieces'],
    extras: ['Spicy Mayo', 'Wasabi Paste', 'Pickled Ginger'],
  ),
  FoodItem(
    id: '4',
    name: 'Decadent Chocolate Lava',
    description: 'Rich dark chocolate cake cooked soft with a warm molten chocolate center that flows out at first spoonful. Served with organic Madagascar vanilla ice cream.',
    price: 8.99,
    imageUrl: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?w=800&auto=format&fit=crop&q=80',
    rating: 4.9,
    prepTime: '10-12 min',
    category: 'Desserts',
    sizes: ['Regular', 'Double Portion'],
    extras: ['Extra Ice Cream', 'Chocolate Sprinkles', 'Strawberry Slices'],
  ),
  FoodItem(
    id: '5',
    name: 'Fresh Mango Smoothie',
    description: 'Creamy blend of ripe organic Alphonso mangoes, Greek yogurt, wildflower honey, and splash of coconut water, served ice cold with crushed mint leaves.',
    price: 5.99,
    imageUrl: 'https://images.unsplash.com/photo-1537640538966-79f369143f8f?w=800&auto=format&fit=crop&q=80',
    rating: 4.5,
    prepTime: '5-7 min',
    category: 'Drinks',
    sizes: ['Medium', 'Large'],
    extras: ['Chia Seeds', 'Protein Boost', 'Whipped Cream'],
  ),
  FoodItem(
    id: '6',
    name: 'Classic Margherita Pizza',
    description: 'Simple and authentic Neapolitan style pizza with fresh san marzano tomato sauce, organic buffalo mozzarella, sweet basil leaves, and a drizzle of extra virgin olive oil.',
    price: 12.99,
    imageUrl: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?w=800&auto=format&fit=crop&q=80',
    rating: 4.6,
    prepTime: '15-20 min',
    category: 'Pizza',
    sizes: ['Small', 'Medium', 'Large'],
    extras: ['Olives', 'Mushrooms', 'Jalapenos'],
  ),
];
